### ISSUE TITLE
The Planetary Network is missing on the app`s menu (IOS)

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#240]
Test case: TC386
Open app on the Iphone (xs)  Version 15.5
App virsion : 3.6.0-143
![image](https://user-images.githubusercontent.com/106578096/173563624-b3ec6363-3aa3-4629-8073-39857911a1f5.png)

**Comment by ken-de-moor** [comment]
This is by design at the moment, iPhone Planetary network is still not working for about 1 in 3 iPhones and has been disabled for now. If you want to test it we can enable it for a specific ThreeFold Connect account in settings, however there is ofcourse the chance that that specific phone won't work.

If you give me a 3bot account name I can enable it for that account.

**Comment by dmitri-alleo** [comment]
@ken-de-moor I guess it's not necessary if it's not used for the iPhones for now,
once it will be decided to be used, we can then test
