### ISSUE TITLE
TC224 - billing of used bandwith - Azmy TBC

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#245]
Can you please be a bit more specific about this test case,  what needs to be tested and where

Updated on:26th Oct 2021 Last saved by:Reem Khamis Associated requirements:0 Test run stats: [View](https://app.testlodge.com/a/26076/projects/40893/reports/steps/3354945/run_stats)
Test steps

    download some files on gw
    should be reflected in billing

**Comment by muhamadazmy** [comment]
Gateway reports (used) capacity (traffic) over the gateway to the contract of the gateway workload. Hence if you are running a service (let's say a file host) behind the gateway and then start downloading files. The traffic downloaded should reflect in the billing of next cycle. 

Testing this can be tricky because 
- we report "used" capacity every hour. 
- the billing cycle on the chain is also every hour. It's not related to the report cycle, so they are not aligned. Each has its own cycle.
- Once billing is triggered on the chain, only an even is emitted but there is no actual token withdraw done. Only locked.
- Each 24 hours the token transfer is done.

**Comment by dmitri-alleo** [comment]
Hmm, I see the mechanism, thanks @muhamadazmy 
Will try looking at it from this perspective and checking via GraphQL as well
