### ISSUE TITLE
Terraform test error - go test returns no such file or directory 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/test_feedback#271]
[terraform-provider-grid](https://github.com/threefoldtech/terraform-provider-grid) on **Ubuntu 20.04.4 LTS** with **Terraform v1.2.6** and **GO 1.18.3**
I export MNEMONICS and NETWORK as required.
I got the following error while running the `go test ./... -p 1`
##### in the terraform-provider-grid directory :
![Screenshot from 2022-08-09 15-04-00](https://user-images.githubusercontent.com/62248851/183654034-cd18994a-cd83-44ac-8ba0-ccd75904d595.png)
`terraform-provider-grid$ go test ./... -p 1 
pkg/subi/contract.go:4:2: github.com/threefoldtech/substrate-client-dev@v0.0.1 (replaced by ./pkg/substrates/substrate-dev): reading pkg/substrates/substrate-dev/go.mod: open /home/o0m4r/codescalers/terraform-provider-grid/pkg/substrates/substrate-dev/go.mod: no such file or directory
pkg/subi/contract.go:5:2: github.com/threefoldtech/substrate-client-dev@v0.0.1 (replaced by ./pkg/substrates/substrate-dev): reading pkg/substrates/substrate-dev/go.mod: open /home/o0m4r/codescalers/terraform-provider-grid/pkg/substrates/substrate-dev/go.mod: no such file or directory
pkg/subi/contract.go:6:2: github.com/threefoldtech/substrate-client-dev@v0.0.1 (replaced by ./pkg/substrates/substrate-dev): reading pkg/substrates/substrate-dev/go.mod: open /home/o0m4r/codescalers/terraform-provider-grid/pkg/substrates/substrate-dev/go.mod: no such file or directory
pkg/subi/contract.go:7:2: github.com/threefoldtech/substrate-client-dev@v0.0.1 (replaced by ./pkg/substrates/substrate-dev): reading pkg/substrates/substrate-dev/go.mod: open /home/o0m4r/codescalers/terraform-provider-grid/pkg/sub
![Screenshot from 2022-08-09 13-04-20](https://user-images.githubusercontent.com/62248851/183653471-75ed4efc-1654-4969-9713-eb85cc317e04.png)
strates/substrate-dev/go.mod: no such file or directory
`

##### also in _/terraform-provider-grid/tests_ directory I got : 
`?   	github.com/threefoldtech/terraform-provider-grid/tests	[no test files]`

**Comment by mohamedamer453** [comment]
- Should be fixed in https://github.com/threefoldtech/terraform-provider-grid/pull/301
- This `? github.com/threefoldtech/terraform-provider-grid/tests [no test files]` was not an issue since it checks the `/tests` directory first then it will run the ones that are in the sub directories where the tests are located. 
- you can also run it using `gotestsum` and it will not show that line

**Comment by mohamedamer453** [comment]
Verified.

The error mentioned originally in this issue was due to outdated docs on how to run the tests. the [docs](https://github.com/threefoldtech/terraform-provider-grid#run-tests) are now updated and the new commands will not result in this error either when using `go test` or `gotestsum`


and as mentioned before 

> * This `? github.com/threefoldtech/terraform-provider-grid/tests [no test files]` was not an issue since it checks the `/tests` directory first then it will run the ones that are in the sub directories where the tests are located.
> * you can also run it using `gotestsum` and it will not show that line

The second part was not a issue it was related to the way `go test` displays the test results. the new docs solves this issue by adding steps on how to install and use `gotestsum` to display the test results in a better way. and you can see how these tests look using `gotestsum` in the logs of the [workflow](https://github.com/threefoldtech/terraform-provider-grid/runs/8173286789?check_suite_focus=true) that runs these tests everyday.

![image](https://user-images.githubusercontent.com/101194226/188308313-5d63af1b-8d16-4a2b-b7a6-292e6ef77949.png)


@0oM4R please feel free to reopen this issue if you're still encountering any of these issues.
