### ISSUE TITLE
Rogue Contract 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#276]
On my Devnet farm (farm 59) i am showing a ipv4 address checked out to contract 5901, there is not current deployments on the node though and this is not one of my contracts. I suspect that is contract is stuck in the null state.

**Comment by DylanVerstraete** [comment]
Not sure where you see this, I can see that your farm has 5 public ips but no node contract is attached:

```js
{
  version: 4
  id: 59
  name: SmithTacDevops
  twinId: 68
  pricingPolicyId: 1
  certification: NotCertified
  publicIps: [
    {
      ip: 162.205.240.252/25
      gateway: 162.205.240.254
      contractId: 0
    }
    {
      ip: 162.205.240.245/25
      gateway: 162.205.240.254
      contractId: 0
    }
    {
      ip: 162.205.240.246/25
      gateway: 162.205.240.254
      contractId: 0
    }
    {
      ip: 162.205.240.247/25
      gateway: 162.205.240.254
      contractId: 0
    }
    {
      ip: 162.205.240.248/25
      gateway: 162.205.240.254
      contractId: 0
    }
    {
      ip: 162.205.240.249/25
      gateway: 162.205.240.254
      contractId: 0
    }
  ]
  dedicatedFarm: false
  farmingPolicyLimits: null
}
```

Also contract 5901 was deleted and is not active anymore

**Comment by mohamedamer453** [comment]
indeed by checking contract details form graphql the contract state was `deleted`

![image](https://user-images.githubusercontent.com/101194226/187880250-414e2129-8b6c-4cf1-82c1-64ed0eddff4c.png)

and as shown from the deployment data it was a `k8s` deployment with a public ip

i'm closing this issue for now since the contract is deleted and no further investigations can be done on it. but feel free to reopen this issue if it occurred again.
