### ISSUE TITLE
Balance suddenly dropped to zero on devnet

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/test_feedback#301]
Added 100 TFTs using [dashboard.dev.grid.tf](url) and had 113 TFTs tried deploying Kubernetes shortly after on [play.dev.grid.tf](url) suddenly balance dropped to 0.005.
twin_id = 192

https://gridproxy.dev.grid.tf/contracts?twin_id=192&&state=Created

**Comment by DylanVerstraete** [comment]
@AbdelrahmanElawady Did you fund your twin again after this happened? Cause when I query all your information of your twin right now everything seems good. You balance is around 120 TFT and you have 3 active contracts.

**Comment by AbdelrahmanElawady** [comment]
@DylanVerstraete Yes, I did fund my twin after it dropped to zero and had 200 TFT. Then I created those 3 contracts.

**Comment by DylanVerstraete** [comment]
@AbdelrahmanElawady I think something like the following happened, your twin had some "outstanding balance" from previous deployments (because most likely your twin was out of balance for a while). This first you funded it, the billing recognised this outstanding balance and withdrew it from your account resulting in having 0 balance again.

Now you refunded your twin again, some outstanding balance was still there and got withdrawn again. Currently I think all outstanding balance is settled and the billing works as intended. I am checking your contract locks and general account lock and everything checks out:

this is your general account lock:

```
[
  {
    id: gridlock
    amount: 185,229,259
    reasons: All
  }
]
```

Locked tokens for contract 15541:

```
{
  amountLocked: 92,623,532
  lockUpdated: 1,666,349,268
  cycles: 18
}
```

Locked tokens for contract 15542:

```
{
  amountLocked: 92,605,727
  lockUpdated: 1,666,349,286
  cycles: 18
}
```


Current total locked balance: `185,229,259` (gridlock)
Current total free balance: `1,341,254,182` 
Current total useable balance: free balance - locked balance

I don't see any issues regarding this billing as it's intended that the outstanding balance for contracts (which were still running after balance on an account dropped below the last amount due) is settled when the account is refunded with tokens

**Comment by DylanVerstraete** [comment]
I also see that the latest k8s vm deployment is already running for 18 hours without issues, so my above statements justify current behaviour.

**Comment by DylanVerstraete** [comment]
Some way to verify if what I am saying above is correct is to do the following:

1: Transfer all the remaining balance from your twin to some other account
2: Wait a couple of hours for your workloads to accumulate some oustanding balance
3: Refund your account with an amount (10 or 100 TFT)
4: Check after one hour how much TFT got withdrawn or locked from your account
5: Check if this amount exceeds the 1 hour bill cost

**Comment by AbdelrahmanElawady** [comment]
@DylanVerstraete  My twin was out of balance for a while and I had some deployments already so that probably was the reason. Now it's working fine.
Thanks :)
