### ISSUE TITLE
Sending TFT between nets causes loss

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#318]
User gerard on the forums has reported an issue with a TFT transfer. 

     "Thanx Guys, It would really help to have more documentation on this and an overview of all the different wallets, Farms 
       and chains. I am new to Threefold so this could be just me.
       I went to testnet on the portal, I clicked on transfer and then I clicked on deposit to.

        I have send the address in a pm to you [@ParkerS](https://forum.threefold.io/u/parkers).
        After that I went to the mainnet and clicked on the name with TFT, clicked on swap/withdraw and then filled in the 
         stellar address from testnet from this picture with my TFT amount. When I go back to my test account from the stellar 
       address I see no change and on main the TFT is swapped. So I managed to do a swap but I don’t know where to" 

'it looks like he sent a transaction that would of come FROM the bridge wallet to the bridge wallet, this appears to have created a transaction that sent without a memo and cannot be returned without a memo. it looks like his tft is caught in the bridge wallet. I directed him to reach on chat aswell. 

Can we add a memo section on dashboard?

**Comment by mohamedamer453** [comment]
The issue was fixed in https://github.com/threefoldtech/tfgrid_dashboard/issues/379 now when the user enters the bridge address it will not be accepted and a validation message will get triggered mentioning that this is a blocked address.

***note: this feature is not available yet on test/mainnet and it will be available with the `3.8` release.
