### ISSUE TITLE
tfmastodon feedback and potential FAQs

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/test_feedback#351]
What's The difference for me as a user to build a mastodon server on certified node vs diy node? Will it also be costing more?

what is exactly 'locked balance' on my account means?

what happens if I forgot to fund my mastodon server? Deactivated, grace period?

can I reactivate a deactivated server

do we send out email notifications to remind people to top up their accounts?

can I join fediverse using my tf mastodon server

also suggestion that before someone delete their server, they need to confirm the deletion with email confirmation or admin username and password, etc if we havent done so

**Comment by samtaggart** [comment]
**Notes (@samtaggart create issues):**

- [x] Link to certified node library information 
- [x] More text in both certified node and threefold connect pop up text
- [x] Link locked balance to the manual (hover text)
- [x] Sasha add "what happens if I forgot to fund my mastodon server" into the manual for mastodon

**Comment by samtaggart** [comment]
Issues created:

https://github.com/threefoldtech/www-mastodon/issues/110
https://github.com/threefoldtech/www-mastodon/issues/98
https://github.com/threefoldfoundation/info_manual3/issues/139

**Comment by sasha-astiadi** [comment]
all checked and item assigned to me is in verification
