### ISSUE TITLE
manual faq - Table of Contents urls leading to 404 error

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/test_feedback#356]
all Table of Contents urls are leading to 404 not found error
https://library.threefold.me/info/manual/#/manual__faq

**Comment by maayarosama** [comment]
The right way to link subsections  `in this publishing system`  in a page should be like the following:
```bash
  [Basic Facts](manual__faq?id=basic-facts)
```
Instead of 
```
[basic facts](#basic-facts)
```
which should work fine in vanilla markdown, but not in the current implementation of the markdown in the publishing system.
Also, the publishingtools validation rules the link used to be either a full https link to a resource or just the page name, without any encoding of divs in it. It can't be fixed without a new release of the publishingtools 

I'll  move to later milestone to be checked again when this gets supported in the publishingtools framework.

**Comment by xmonader** [comment]
Would gladly accept PRs against the new manual 
https://github.com/threefoldtech/info_grid

**Comment by fl0wm0ti0n** [comment]
nice , with PRs you mean pull requests?
