### ISSUE TITLE
The entire grid is reporting down

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#363]
Entire grid is showing down on the explorer and by /status in the status bot. 

![B8896830-6FDF-4289-B43E-38BF1E75CC50](https://user-images.githubusercontent.com/44621168/208282458-f11642b4-6725-44bf-bb28-c323cb93d43c.png)

/ping is functioning in the status bot

**Comment by hossnys** [comment]
that happened because of indexer ( one of our tf-chain components ) was out of sync because of network timeout , and it synced again now , all nodes showing up now in explorer .
![Screenshot from 2022-12-18 09-24-56](https://user-images.githubusercontent.com/26298009/208287176-8a0570cb-e7f9-4112-972a-d1fc031ad811.png)
